apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ossm3x/application.yaml
  - Tempo/application.yaml
  - OpenTelemetry/application.yaml
  - Kiali/application.yaml
  - Keycloak/application.yaml
  - StreamsForApacheKafka/application.yaml
  - StreamsForApacheKafkaProxy/application.yaml
