apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#operator selection
- ../../demo-dep/operators/ossm3x
- ../../demo-dep/operators/Tempo
- ../../demo-dep/operators/OpenTelemetry
- ../../demo-dep/operators/Kiali
- ../../demo-dep/operators/Keycloak
