apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demodep-argocd
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    dependency: observability
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: https://github.com/axodevelopment/homedemo-setup
    targetRevision: main
    path: demo-dep/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
