apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-day2-basicsetup-application.yaml
- infra-application.yaml
- demodep-argocd-application.yaml
- live-application.yaml