apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dd-operators-streamsforapachekafka
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    dependency: observability
spec:
  project: infra
  source:
    repoURL: https://github.com/axodevelopment/homedemo-setup
    targetRevision: main
    path: demo-dep/operators/StreamsForApacheKafka
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
